FROM golang:1.24-alpine
LABEL org.opencontainers.image.authors="CyberArk Software Ltd."
LABEL id="sidecar-injector-test-runner"

# On CyberArk dev laptops, golang module dependencies are downloaded with a
# corporate proxy in the middle. For these connections to succeed we need to
# configure the proxy CA certificate in build containers.
#
# To allow this script to also work on non-CyberArk laptops where the CA
# certificate is not available, we copy the (potentially empty) directory
# and update container certificates based on that, rather than rely on the
# CA file itself.
ADD build_ca_certificate /usr/local/share/ca-certificates/
RUN update-ca-certificates

WORKDIR /sidecar-injector

RUN apk add -u curl \
    gcc \
    git \
    mercurial \
    musl-dev

COPY go.mod go.sum /sidecar-injector/

COPY . .

ENTRYPOINT [ "go", "test", "-v" ]
