#!/bin/bash

#set -euo pipefail

# Sets additional required environment variables that aren't available in the
# secrets.yml file, and performs other preparatory steps
function prepareTestEnvironment() {
    # Prepare Docker images
    pushd tests || exit 1
    docker build --rm --tag "gke-utils:latest" . >/dev/null
    popd || exit 1
}

function runDockerCommand() {
    docker run --rm \
      -i \
      -e DOCKER_REGISTRY_URL \
      -e DOCKER_REGISTRY_PATH \
      -e GCLOUD_SERVICE_KEY="/tmp${GCLOUD_SERVICE_KEY}" \
      -e GCLOUD_CLUSTER_NAME \
      -e GCLOUD_ZONE \
      -e GCLOUD_PROJECT_NAME \
      -e SIDECAR_IMAGE \
      -e SECRETLESS_IMAGE \
      -e SECRETLESS_CRD_SUFFIX \
      -e UNIQUE_TEST_ID \
      -e TEST_NAMESPACE \
      -v "${GCLOUD_SERVICE_KEY}:/tmp${GCLOUD_SERVICE_KEY}" \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v ~/.config:/root/.config \
      -v "$PWD":/src \
      -w /src \
      "gke-utils:latest" \
      bash -xec "
        pwd
        ./tests/platform_login > /dev/null
        $1
      "
}

function announce() {
    echo "++++++++++++++++++++++++++++++++++++++"
    echo ""
    echo "$@"
    echo ""
    echo "++++++++++++++++++++++++++++++++++++++"
}
