apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cyberark-sidecar-injector
  labels:
    app: cyberark-sidecar-injector
webhooks:
  - name: sidecar-injector.conjur.org
    clientConfig:
      service:
        name: ${service}
        namespace: ${namespace}
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    namespaceSelector:
      matchLabels:
        ${namespaceSelectorLabel}: enabled
