---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configurations.secretless{{ .Values.SECRETLESS_CRD_SUFFIX }}.io
spec:
  group: secretless{{ .Values.SECRETLESS_CRD_SUFFIX }}.io
  names:
    kind: Configuration
    plural: configurations
    singular: configuration
    shortNames:
    - sbconfig
  scope: Namespaced
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
