apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "cyberark-sidecar-injector.name" . }}.{{ .Release.Namespace }}
  labels:
    app: {{ include "cyberark-sidecar-injector.name" . }}
    chart: {{ include "cyberark-sidecar-injector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
webhooks:
  - name: sidecar-injector.conjur.org
    clientConfig:
      service:
        name: {{ include "cyberark-sidecar-injector.name" . | quote }}
        namespace: {{ .Release.Namespace | quote }}
        path: "/mutate"
      caBundle: {{ (required "A valid .Values.caBundle entry required!" .Values.caBundle) | b64enc | quote }}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    namespaceSelector:
      matchLabels:
        {{ (required "A valid .Values.namespaceSelectorLabel entry required!" .Values.namespaceSelectorLabel) }}: enabled
