apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "cyberark-sidecar-injector.name" . }}-service-account-token
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    kubernetes.io/service-account.name: {{ include "cyberark-sidecar-injector.name" . }}
